name: Add or Update C3 ETH Page
description: "Add or update a page/document to the C3 ETH Website."
title: ":page_facing_up: Add new page/document for <TITLE>"
labels: ["documentation", "help wanted"]
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: We welcome contributions and suggestions from our community. Any improvements help. Please fill out the details of your suggestion for adding or updating content on the Cardano Catalyst Community (C3) Eastern Townhall website.

  - type: input
    id: page-title
    attributes:
      label: Page Title
      description: "The first thing to do is to replace the text *<TITLE>* in the issue title above with a very short description of the change you want. Add a longer title here."
      placeholder: "<DOCUMENT TITLE>"
    validations:
      required: true

  - type: textarea
    id: short-description
    attributes:
      label: Description of change
      description: Please write a short outline of the change you want to see.
      placeholder: Add/Update the website with the following changes...
    validations:
      required: true

  - type: dropdown
    id: add-or-change
    attributes:
      label: Is your suggestion and addition, or a change?
      description: Please tell us if this a new page or just a change to an existing one.
      options:
        - Add a new page
        - Change to exisitng page
    validations:
      required: true

  - type: checkboxes
    id: language
    attributes:
      label: "Which language does the change effect?"
      options:
        - label: English
        - label: Indonesian
        - label: Japanese
        - label: Korean
        - label: Vietnamese

  - type: dropdown
    id: page-section
    attributes:
      label: "Which section of the website should the change be made?"
      options:
        - Catalyst Guides
        - Blog Post
        - Catalyst Proposals
        - Catalyst Challenges        
        - Cardano Documentation
        - Tutorials
        - Getting Started
        - Contribution Guidelines
        - Technical Documentation
        - About
        - Home Page
        - Catalyst ETH Proposal
    validations:
      required: true
  
  - type: input
    id: webpage-url
    attributes:
      label: Website URL
      description: "If this is a change to an existing page on our website, what is page's URL?"
      placeholder: "https://c3eth.github.io/"
    validations:
      required: false