name: Add or Update C3 ETH Page
description: "Add or update a page/document to the C3 ETH Website."
title: ":page_facing_up: Add new page/document for <TITLE>"
labels: ["documentation", "help wanted"]
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: We welcome contributions and suggestions from our community. Any improvements help. Please fill out the details of your suggestion for adding or updating content on the Cardano Catalyst Community (C3) Eastern Townhall website.
  - type: markdown
    attributes:
      value: "### Change the issue <TITLE>"
  - type: markdown
    attributes:
      value: The first thing to do is to replace the text *<TITLE>* in the issue title above with a very short description of the change you want.
  - type: textarea
    id: short-description
    attributes:
      label: Description of change
      description: Please write a short outline of the change you want to see.
      placeholder: Add/Update the website with the following changes...
    validations:
      required: true